# Generated by Django 4.0.2 on 2022-02-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manatal', '0003_alter_student_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='identification',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
