# Generated by Django 4.0.3 on 2022-03-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manatal', '0005_school_students_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
