# Generated by Django 4.0.3 on 2022-03-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manatal', '0006_student_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
